-- Hand-written (not autogenerated): Prisma's diff engine treats a field
-- rename as drop+add, which would destroy existing experience_entries data.
-- RENAME COLUMN preserves it instead.
ALTER TABLE "experience_entries" RENAME COLUMN "title" TO "role";
ALTER TABLE "experience_entries" RENAME COLUMN "company" TO "organization";

ALTER TABLE "experience_entries" ADD COLUMN "description" TEXT;
ALTER TABLE "experience_entries" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;

-- Soft-disable for availability rules (see schema.prisma comment).
ALTER TABLE "availability_rules" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;

-- Mentor contact number for the PHONE connection mode (no telephony infra).
ALTER TABLE "mentor_profiles" ADD COLUMN "phone" TEXT;

-- Per-offering connection modes (may be a subset of the mentor's general
-- MentorProfile.connectionModes capability list).
ALTER TABLE "offerings" ADD COLUMN "connectionModes" "ConnectionMode"[];
UPDATE "offerings" SET "connectionModes" = '{}' WHERE "connectionModes" IS NULL;
